import re
import os
from collections import defaultdict
from typing import List, Dict, Any
from src.utils.logger import setup_logger

logger = setup_logger("sentence_splitter")

# Regular expression pattern to split text into sentences.
# Avoids splitting on abbreviations like e.g., i.e., Dr., etc.
#
# Note: we intentionally split only on `.` and `?`, NOT on `!`. The labeled
# dataset at ``data/labeled/labeled_sentences.csv`` (1800 rows, Sprint 3C)
# references sentence_ids generated by this regex; changing the boundary set
# would shift the global counter and invalidate every labeled ID. Academic
# papers and docs (the MVP corpus) almost never use `!`, so the trade-off
# favours preserving the labeled mapping.
SENTENCE_SPLIT_REGEX = re.compile(r'(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s')

def split_into_sentences(text: str) -> List[str]:
    """
    Split text into individual sentences.

    Regex is the default MVP path because some local NLTK/NumPy builds can
    fail at native import time before Python can catch the exception. Set
    CHRONORAG_USE_NLTK=1 to opt into NLTK tokenization in a stable environment.
    """
    if not text:
        return []

    if os.getenv("CHRONORAG_USE_NLTK", "").strip().lower() in {"1", "true", "yes"}:
        try:
            import nltk
            nltk.data.find("tokenizers/punkt")
            sentences = nltk.sent_tokenize(text)
            return [s.strip() for s in sentences if s.strip()]
        except Exception as e:
            logger.warning(f"NLTK sentence tokenization failed: {e}. Falling back to regex splitting.")

    sentences = [s.strip() for s in SENTENCE_SPLIT_REGEX.split(text) if s.strip()]
        
    return [s.strip() for s in sentences if s.strip()]

def split_chunks_into_sentences(chunks: List[Dict[str, Any]], min_sentence_len: int = 15) -> List[Dict[str, Any]]:
    """Split each chunk into sentences and map metadata.

    Sentence IDs and ``sentence_index`` use a **global counter** across the
    whole corpus, not a per-document one. This is intentional: the labeled
    dataset at ``data/labeled/labeled_sentences.csv`` references these exact
    IDs (e.g. ``agent_005_s1226`` means the 1226th sentence in the global
    iteration order, which happens to belong to ``agent_005``). Switching to
    a per-document counter would break that mapping.

    ``position_in_doc`` is added as an extra 1-based ordinal within each
    document for callers that want a doc-relative position without parsing
    the suffix.
    """
    all_sentences = []
    sentence_index = 1
    doc_position: Dict[str, int] = defaultdict(int)

    for chunk in chunks:
        doc_id = chunk.get("doc_id", "")
        chunk_id = chunk.get("chunk_id", "")
        topic = chunk.get("topic", "")
        source_url = chunk.get("source_url", "")
        year = chunk.get("year", None)

        raw_sentences = split_into_sentences(chunk.get("text", ""))

        for sent_text in raw_sentences:
            if len(sent_text) < min_sentence_len:
                continue

            doc_position[doc_id] += 1
            sent_dict = {
                "sentence_id": f"{doc_id}_s{sentence_index:04d}",
                "doc_id": doc_id,
                "chunk_id": chunk_id,
                "topic": topic,
                "sentence_index": sentence_index,
                "position_in_doc": doc_position[doc_id],
                "text": sent_text,
                "source_url": source_url,
                "year": year,
            }
            all_sentences.append(sent_dict)
            sentence_index += 1

    return all_sentences
